repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black

# -   repo: https://github.com/pycqa/flake8
#     rev: '3.9.1'
#     hooks:
#     -   id: flake8

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v0.812'
#     hooks:
#     -   id: mypy

# -   repo: local
#     hooks:
#     -   id: black
#         name: Format python code
#         entry: pipenv run format
#         pass_filenames: false
#         language: system
#         types: [python]
