name: Publish To PyPi and TestPyPi

on:
  workflow_dispatch:
    branches:
      - ${GITHUB_REF##*/}
  push:
    branches:
      - master
      - development

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Build
        run: pipenv run build

      - name: Generate Docs
        run: pipenv run documentation

      - name: Deploy Docs 🚀
        if: startsWith(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
